- name: install nginx
  hosts: web
  become:
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: nginx status
    ansible.builtin.service:
      name: nginx
      state: stopped