- name: install net-tools
  hosts: web
  become: yes
  tasks:
  - name: install net-tools
    ansible.builtin.package:
      name: net-tools
      state: present
  - name: stop nginx
    ansible.builtin.service:
      name: net-tools
      state: stopped
  - name: nginx start
    ansible.builtin.service:
      name: nginx
      state: started