- name: install net-tools
  hosts: web
  become: yes
  tasks:
  - name: install net-tools
    ansible.builtin.package:
      name: net-tools
      state: present
  - name: net-tools start
    ansible.builtin.service:
      name: net-tools
      state: started
  - name: stop net-tools
    ansible.builtin.service:
      name: net-tools
      state: stopped
  