- name: install ngnix
  hosts: web
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.package:
      name: ngnix
      state: present
  - name: ngnix start
    ansible.builtin.service:
      name: ngnix
      state: started
  - name: stop ngnix
    ansible.builtin.service:
      name: ngnix
      state: stopped
  