- name: variables
  hosts: localhost
  vars:
    name1: "Viswanath"
    name2: "Siliveru"
  tasks:
    - name: Print variable test
      ansible.builtin.debug:
        msg:
          - "my name is {{name1}}"
          - "my name is {{name2}}"
