- name: checking data types
  hosts: localhost
  vars:
    Name: S Viswanath
    skill:
    - devops
    - Windows
    - VMware
    Experience:
      devops: 2
      windows: 10
      vmware: 10
    Trainer: true
  tasks:
    - name: print key
      ansible.builtin.debug:
        msg: "{{Name}}"
    - name: print map
      ansible.builtin.debug:
        msg: "{{skill}}"
    - name: print list
      ansible.builtin.debug:
        msg: "{{Experience}}"
    - name: print bool
      ansible.builtin.debug:      
        msg: "{{Trainer}}"
