- name: checking data types
  hosts: localhost
  vars:
    Name: S Viswanath
    skill:
      - devops
      - Windows
      - VMware
    Experience:
      devops: 2
      windows: 10
      vmware: 10
    Boolean: true
  tasks:
    - name: data types
      ansible.builtin.debug:
        - msg: "{{Name}}"
        - msg: "{{skill}}"
        - msg: "{{Experience}}"
        - msg: "{{Bool}}"
