- name: checking data types
  hosts: localhost
  vars:
    Name: "S Viswanath"
    skill:
      - devops
      - Windows
      - VMware
    Experience:
      devops
      windows
      vmware
    Bool: true
  
  tasks:
    ansible.builtin.debug:
      msg: {{Name}}

  tasks:
    ansible.builtin.debug:
      msg: {{skill}}

  tasks:
    ansible.builtin.debug:
      msg: {{Experince}}
  
  tasks:
    ansible.builtin.debug:
      msg: {{Bool}}