- name: Conditions
  hosts: localhost
  tasks:
  - name: check roboshot user
    ansible.builtin.command: id roboshop
    register: "out"
    ignore_errors: true

  - name: print user
    ansible.builtin.debug:
      msg: "User name is {{out}}"

  - name: check user exit output
    ansible.builtin.debug:
      msg: "User name is {{out.rc}}"
  - name: check user exist or not
    ansible.builtin.user:
      - name: roboshop
    when out !=0
  
  
  

