- name: Conditions
  hosts: localhost
  tasks:
  - name: check roboshot user
    ansible.builtin.command: id viswa
    register: "out"

  - name: print user
    ansible.builtin.debug:
      msg: "User name is {{out}}"

