- name: loops
  hosts: localhost
  tasks:
    - name: loop with packages
      ansible.builtin.package:
        name: {{item}}
        state: present
      loop:
      - git
      - mysql
      - net-tools